'use strict';
const app=document.querySelector('#app'),nav=document.querySelector('#nav');let data,round=[],index=0,answers=[],locked=false,sessionLabel='',sessionSource=[],examMode=false,sessionReturn='oefenen';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isText=v=>typeof v==='string';
const isTextList=v=>Array.isArray(v)&&v.every(isText);
const isPage=v=>Number.isInteger(v)&&v>=1&&v<=47;
const isTopicId=v=>Number.isInteger(v)&&v>=1&&v<=6;
const isTopicPages=v=>isText(v)&&/^\d{1,2}(?:[–-]\d{1,2})?(?:, \d{1,2}(?:[–-]\d{1,2})?)*$/.test(v);
const isAsset=v=>typeof v==='string'&&/^assets\/[a-z0-9-]+\.(?:png|jpe?g|webp)$/i.test(v);
const isTarget=v=>Array.isArray(v)&&v.length===2&&v.every(n=>Number.isFinite(n)&&n>=0&&n<=100);
const allowedExternalHosts=new Set(['apk-handboek.rdw.nl','www.hunter.com']);
const isSafeExternalUrl=v=>{if(!isText(v)||/[<>"'\\\s]/.test(v))return false;try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&allowedExternalHosts.has(u.hostname)}catch{return false}};
const isValidData=d=>Boolean(d&&
  Array.isArray(d.topics)&&d.topics.length===6&&d.topics.every(t=>t&&isTopicId(t.id)&&isText(t.title)&&isTopicPages(t.pages)&&isText(t.summary)&&isTextList(t.learn)&&isTextList(t.practice))&&
  Array.isArray(d.questions)&&d.questions.length>0&&d.questions.every(q=>q&&isText(q.id)&&isTopicId(q.topic)&&isPage(q.page)&&isText(q.prompt)&&isText(q.answer)&&Array.isArray(q.choices)&&q.choices.length===4&&q.choices.every(isText)&&new Set(q.choices).size===4&&q.choices.includes(q.answer)&&isText(q.explanation)&&isText(q.kind)&&(q.image==null||isAsset(q.image))&&(q.target==null||isTarget(q.target)))&&
  Array.isArray(d.tools)&&d.tools.every(t=>t&&isText(t.name)&&isText(t.desc)&&isPage(t.page)&&(t.image==null||isAsset(t.image)))&&
  isTextList(d.lamps)&&
  Array.isArray(d.vocabulary)&&d.vocabulary.every(v=>v&&isText(v.name)&&isText(v.desc)&&isText(v.group)&&isPage(v.page))&&
  Array.isArray(d.open)&&d.open.every(q=>q&&isTopicId(q.topic)&&isPage(q.page)&&isText(q.prompt)&&isText(q.answer))&&
  d.exam&&isTextList(d.exam.certain)&&isTextList(d.exam.likely)&&isTextList(d.exam.unknown)&&isTextList(d.exam.later)&&isText(d.exam.laterNote)&&
  Array.isArray(d.nextModules)&&d.nextModules.every(m=>m&&isText(m.title)&&isTextList(m.items)&&isPage(m.page))&&
  Array.isArray(d.notes)&&d.notes.every(n=>n&&isText(n.title)&&isText(n.text)&&isPage(n.page)&&(n.url===undefined||isSafeExternalUrl(n.url)))
);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const source=p=>`<a class="source" href="werkboek.pdf#page=${Number(p)}" target="_blank" rel="noopener">Werkboek · p. ${Number(p)} ↗</a>`;
const list=items=>`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const imageHTML=(q,answer=false)=>q.image?`<figure class="question-image"><div class="image-wrap"><img src="${q.image}" alt="${answer?esc(q.answer):'Afbeelding uit het werkboek bij deze vraag'}">${q.target?`<span class="target" aria-label="Aangewezen gereedschap" style="left:${q.target[0]}%;top:${q.target[1]}%"></span>`:''}</div><figcaption>Foto of tekening uit jouw werkboek · p. ${q.page}</figcaption></figure>`:'';
function render(html,view='oefenen'){if(!html.includes('question-card'))window.QuizMusic?.stop();app.innerHTML=html;app.dataset.view=view;nav.innerHTML=[['oefenen','Oefenen'],['banden','Banden'],['leren','Leerstof'],['woorden','Namen & woorden'],['open','Open vragen'],['examen','Wat kan ik verwachten?']].map(([id,label])=>`<button data-view="${id}" ${id===view?'aria-current="page"':''}>${label}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.view));window.scrollTo(0,0);app.focus({preventScroll:true})}
function go(view){({oefenen:home,banden,leren:learn,woorden:words,open:openQuestions,examen:examInfo}[view]||home)()}
function banden(){window.BandenModule.render({render,start,esc,source,allQuestions:data.questions,shuffle})}
function home(){
  const names=data.questions.filter(q=>q.topic===1&&q.kind==='Naam herkennen');
  render(`
    <div class="dashboard-heading"><div><span class="eyebrow muted">Basismodule mobiliteit · Periode 1</span><h1>Wat ga je oefenen?</h1><p>Kies een onderwerp. Oefen op jouw tempo.</p></div><div class="question-count"><b>${data.questions.length}</b><span>vragen met uitleg</span></div></div>
    <div class="study-launcher">
      <section class="tire-feature"><div class="feature-copy"><span class="feature-label">${window.BandenModule.questions.length} extra oefenvragen</span><h2>Van wang<br>tot karkas.</h2><p>Ontdek de band van binnenuit.<br>Onderdelen, codes en controles.</p><button class="btn" id="banden">Banden oefenen <span aria-hidden="true">↗</span></button></div><div class="feature-diagram"><img src="assets/band-delen.png" width="893" height="778" alt="Doorsnede van een band met de benoemde onderdelen"><span>Loopvlak · schouder · wang · hiel</span></div></section>
      <div class="side-launcher"><button class="launch-card" id="names"><span class="launch-top"><span class="eyebrow muted">Namen leren</span><span class="launch-symbol" aria-hidden="true">01</span></span><b>Ken je gereedschap.</b><span>${names.length} namen met de foto’s uit je werkboek.</span><span class="launch-link">Begin met oefenen <span aria-hidden="true">↗</span></span></button><button class="launch-card exam-launch" id="test"><span class="launch-top"><span class="eyebrow muted">Kennis testen</span><span class="launch-symbol" aria-hidden="true">02</span></span><b>Klaar voor een proeftoets?</b><span>30 vragen · alle 6 onderwerpen · geen timer</span><span class="launch-link">Start de proeftoets <span aria-hidden="true">↗</span></span></button></div>
    </div>
    <div class="practice-strip"><div><span class="strip-number">6</span><span>onderwerpen uit<br><b>jouw schoolwerkboek</b></span></div><button class="quiet" id="all">Alles door elkaar oefenen →</button><button class="quiet" id="expect">Wat moet ik kennen?</button></div>
    <section><div class="section-head"><h2>Jouw onderwerpen</h2><span>Lezen, oefenen en opnieuw proberen</span></div><div class="topic-grid">${data.topics.map(t=>`<article class="topic"><div class="topic-meta"><span class="topic-num">0${t.id}</span><span class="topic-pages">p. ${esc(t.pages)}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><div class="topic-bottom"><button class="btn secondary" data-topic="${t.id}">Oefenen · ${data.questions.filter(q=>q.topic===t.id).length}</button><button class="quiet" data-learn="${t.id}">Leerstof</button></div></article>`).join('')}</div></section>
    <p class="notice">De proeftoets is een oefening, geen officiële toets. Vraag je docent naar de echte toetsvorm en beoordeling.</p>
  `);
  document.querySelector('#banden').onclick=banden;
  document.querySelector('#names').onclick=()=>start(names,'Alleen gereedschapsnamen');
  document.querySelector('#all').onclick=()=>start(data.questions,'Alle onderwerpen');
  document.querySelector('#test').onclick=()=>start(data.topics.flatMap(t=>shuffle(data.questions.filter(q=>q.topic===t.id)).slice(0,5)),'Proeftoets',true);
  document.querySelector('#expect').onclick=examInfo;
  document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>start(data.questions.filter(q=>q.topic===+b.dataset.topic),data.topics.find(t=>t.id===+b.dataset.topic).title));
  document.querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>learn(+b.dataset.learn));
}
function start(qs,label,isExam=false,returnView='oefenen'){if(!Array.isArray(qs)||!qs.length)return;sessionReturn=returnView==='banden'?'banden':'oefenen';sessionSource=[...qs];sessionLabel=label;examMode=isExam;round=shuffle(qs).map(q=>({...q,choices:shuffle(q.choices)}));index=0;answers=[];show();window.QuizMusic?.start()}
function show(){locked=false;const q=round[index];render(`<div class="topline"><button class="quiet" id="home">← ${sessionReturn==='banden'?'Banden':'Oefenoverzicht'}</button><b>Vraag ${index+1} / ${round.length}</b><span>${examMode?'Zonder tijdslimiet':answers.filter(a=>a.correct).length+' goed'}</span></div><div class="progress" role="progressbar" aria-label="Voortgang" aria-valuemin="0" aria-valuemax="${round.length}" aria-valuenow="${index}"><div style="width:${index/round.length*100}%"></div></div><section class="question-card"><div class="qbody ${q.image?'':'noimage'}">${imageHTML(q)}<div><span class="eyebrow muted">${esc(sessionLabel)} · ${esc(q.kind)}</span><h2>${esc(q.prompt)}</h2><div class="options">${q.choices.map((c,i)=>`<button class="option" data-i="${i}"><span class="letter">${'ABCD'[i]}</span><span>${esc(c)}</span></button>`).join('')}</div><div id="feedback" aria-live="polite"></div>${examMode?'':source(q.page)}</div></div></section>`,sessionReturn);document.querySelector('#home').onclick=()=>go(sessionReturn);document.querySelectorAll('.option').forEach(b=>b.onclick=()=>choose(+b.dataset.i))}
function choose(i){if(locked||!Number.isInteger(i)||i<0||i>3)return;locked=true;const q=round[index],choice=q.choices[i],correct=choice===q.answer;answers.push({q,choice,correct});document.querySelectorAll('.option').forEach((b,j)=>{b.disabled=true;if(examMode){if(j===i)b.classList.add('selected')}else if(q.choices[j]===q.answer)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});document.querySelector('#feedback').innerHTML=`<div class="feedback ${!correct&&!examMode?'bad':''}"><strong>${examMode?'Antwoord opgeslagen':correct?'Goed gedaan!':'Nog even oefenen'}</strong>${examMode?'<p>Je ziet de antwoorden en uitleg na de laatste vraag.</p>':`<p>${correct?'':`Goed antwoord: <b>${esc(q.answer)}</b>.<br>`}${esc(q.explanation)}</p>`}<button class="btn" id="next">${index===round.length-1?'Bekijk je resultaat':'Volgende vraag →'}</button></div>`;document.querySelector('#next').onclick=()=>{index++;index<round.length?show():result()};document.querySelector('#next').focus({preventScroll:true})}
function result(){const wrong=answers.filter(a=>!a.correct),good=answers.length-wrong.length;const review=examMode?answers:wrong;render(`<section class="result"><span class="eyebrow">${esc(sessionLabel)} · afgerond</span><h2>${wrong.length?'Je weet nu wat je nog kunt oefenen.':'Alles goed. Netjes gewerkt!'}</h2><div class="score">${good}<span> / ${answers.length}</span></div><p>${Math.round(good/answers.length*100)}% goed${examMode?' · Oefenresultaat, geen officieel schoolcijfer':''}</p><div class="actions"><button class="btn" id="again">Deze ronde opnieuw</button>${wrong.length?'<button class="btn secondary" id="retry">Oefen mijn fouten</button>':''}<button class="btn secondary" id="home">${sessionReturn==='banden'?'Terug naar banden':'Oefenoverzicht'}</button></div></section>${review.length?`<section class="review"><h2>${examMode?'Antwoorden en uitleg':'Dit kun je nog oefenen'}</h2>${review.map(a=>`<article>${imageHTML(a.q,true)}<div><span class="eyebrow ${a.correct?'muted':''}">${a.correct?'Goed':'Nog oefenen'}</span><h3>${esc(a.q.prompt)}</h3><p>Jouw antwoord: ${esc(a.choice)}</p><p><b>Goed antwoord: ${esc(a.q.answer)}</b></p><p>${esc(a.q.explanation)}</p>${source(a.q.page)}</div></article>`).join('')}</section>`:''}`);document.querySelector('#again').onclick=()=>start(sessionSource,sessionLabel,examMode,sessionReturn);document.querySelector('#home').onclick=()=>go(sessionReturn);if(wrong.length)document.querySelector('#retry').onclick=()=>start(wrong.map(a=>a.q),'Mijn fouten',false,sessionReturn)}
function learn(selected){render(`<div class="page-heading"><span class="eyebrow muted">Alle 6 opdrachten · p. 1–47</span><h1>Dit moet je leren.</h1><p>Korte samenvattingen, praktijkwerk en een link naar de juiste bladzijde.</p></div>${data.topics.map(t=>`<details class="lesson" id="topic-${t.id}" ${selected===t.id?'open':''}><summary><span class="topic-num">0${t.id}</span><span>${esc(t.title)}<small>Werkboek p. ${t.pages}</small></span></summary><div class="lesson-content"><p>${esc(t.summary)}</p><h3>Kennen en begrijpen</h3>${list(t.learn)}<h3>Zelf doen in de werkplaats</h3>${list(t.practice)}<p class="notice">Praktijkwerk doe je met de uitleg en begeleiding van je docent. Een quiz vervangt de praktijkbeoordeling niet.</p><button class="btn" data-practice="${t.id}">Oefen dit onderwerp</button> ${source(parseInt(t.pages))}${t.id===1?`<div class="gallery">${[9,10,11,12,13,14].map(n=>`<a href="werkboek.pdf#page=${n}" target="_blank" rel="noopener"><img loading="lazy" src="assets/page-${n}.png" alt="Gereedschapslade op pagina ${n}"><span>Pagina ${n}</span></a>`).join('')}</div>`:''}${t.id===2?`<a href="werkboek.pdf#page=20" target="_blank" rel="noopener"><img class="diagram" loading="lazy" src="assets/page-20.png" alt="Auto-onderdelen benoemen, schoolopdracht pagina 20"></a>`:''}${t.id===4?'<img class="diagram" loading="lazy" src="assets/band-delen.png" alt="Benoemde delen van een band"><a href="werkboek.pdf#page=28" target="_blank" rel="noopener">Bekijk de volledige draaggetal- en snelheidstabel op pagina 28</a>':''}${t.id===5?'<img class="diagram" loading="lazy" src="assets/page-37.png" alt="Diepbed en bandenmachine met benoemde onderdelen">':''}</div></details>`).join('')}<section class="card"><h2>Zo werk je het boek af</h2>${list(['Neem veiligheidsschoenen en geschikte werkkleding mee.','Volg de theorie en lees alvast de vakboekopdracht.','Doe één opdracht tegelijk en maak die af voordat je verdergaat.','Voer de praktijk uit en werk je vakboek digitaal uit.','Vaktaal is extra; overleg eerst met klasgenoten als dat bij de opdracht mag.','Laat de kennis- en vaardighedenlijst aftekenen en bewaar een foto als reserve.'])}${source(2)} ${source(3)}</section><section class="card"><h2>Let op bij deze passages</h2>${data.notes.map(n=>`<details><summary>${esc(n.title)}</summary><p>${esc(n.text)}</p>${source(n.page)}${n.url?` · <a href="${n.url}" target="_blank" rel="noopener">Controlebron</a>`:''}</details>`).join('')}</section>`,'leren');document.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>start(data.questions.filter(q=>q.topic===+b.dataset.practice),data.topics.find(t=>t.id===+b.dataset.practice).title));if(selected)document.querySelector('#topic-'+selected).scrollIntoView({block:'start'})}
function words(){render(`<div class="page-heading"><span class="eyebrow muted">Namen zoals in jouw schoolboek</span><h1>Kijk. Benoem. Herhaal.</h1><p>Gereedschappen en dashboardlampjes met de originele foto’s. Bekijk daarna de woorden uit alle checklists.</p></div><label class="search-label" for="word-search">Zoek een naam</label><input type="search" id="word-search" placeholder="Bijvoorbeeld: ratel, wang, motorkap…"><div id="word-results"></div>`,'woorden');const items=[...data.tools.map(t=>({...t,group:'Gereedschap'})),...data.lamps.map((name,i)=>({name,desc:'Naam van het lampje in het werkboek. Raadpleeg het voertuigboek voor de reactie op een waarschuwing.',page:21,image:`assets/lamp-${i}.png`,group:'Dashboardlampjes'})),...data.vocabulary];const display=()=>{const term=document.querySelector('#word-search').value.toLocaleLowerCase('nl');const found=items.filter(x=>(x.name+' '+x.desc+' '+x.group).toLocaleLowerCase('nl').includes(term));document.querySelector('#word-results').innerHTML=`<p class="muted" aria-live="polite">${found.length} namen</p><div class="word-grid">${found.map(x=>`<article class="word-card">${x.image?imageHTML({...x,answer:x.name},true):''}<span class="eyebrow muted">${esc(x.group)}</span><h3>${esc(x.name)}</h3><p>${esc(x.desc)}</p>${source(x.page)}</article>`).join('')}</div>${found.length?'':'<p>Geen naam gevonden. Probeer een korter woord.</p>'}`};document.querySelector('#word-search').oninput=display;display()}
function openQuestions(){render(`<div class="page-heading"><span class="eyebrow muted">Uitleggen in je eigen woorden</span><h1>Oefen je open antwoorden.</h1><p>Schrijf eerst zelf. Vergelijk daarna met het voorbeeld. Je antwoord wordt niet automatisch beoordeeld of opgeslagen.</p></div><div class="open-list">${data.open.map((q,i)=>`<article class="card"><span class="eyebrow muted">${esc(data.topics.find(t=>t.id===q.topic).title)}</span><h2>${esc(q.prompt)}</h2><label for="answer-${i}">Jouw antwoord in het Nederlands</label><textarea id="answer-${i}" rows="3" placeholder="Schrijf wat jij weet…"></textarea><details><summary>Bekijk een voorbeeldantwoord</summary><p>${esc(q.answer)}</p></details>${source(q.page)}</article>`).join('')}</div>`,'open')}
function examInfo(){render(`<div class="page-heading"><span class="eyebrow muted">Gebaseerd op jouw 47 pagina’s</span><h1>Wat kan ik verwachten?</h1><p>Dit onderscheid helpt je gericht leren zonder een gok als zekerheid te zien.</p></div><section class="card"><span class="tag">Staat in het boek</span><h2>De toets van de basismodule</h2>${list(data.exam.certain)}${source(1)} ${source(2)} ${source(3)}<div class="topic-grid compact">${data.topics.map(t=>`<div><b>${t.id}. ${esc(t.title)}</b><p>p. ${t.pages}</p></div>`).join('')}</div></section><section class="card"><span class="tag">Afgeleid van de opdrachten</span><h2>Vraagvormen om op te oefenen</h2>${list(data.exam.likely)}<button class="btn" id="test">Doe een proeftoets · 30 vragen</button> <button class="btn secondary" id="open">Oefen open vragen</button></section><section class="card"><h2>Dit weten we nog niet</h2>${list(data.exam.unknown)}<p>Vraag je docent naar toetsdatum, toetsvorm, toegestane hulpmiddelen en de officiële beoordeling.</p></section><section class="card"><span class="tag">Later · Periode 4</span><h2>Praktijkexamen in het opleidingsoverzicht</h2><p>${esc(data.exam.laterNote)}</p>${list(data.exam.later)}${source(5)}</section><section class="card"><h2>Overzicht van de rest van je opleiding</h2><p>Pagina 4–5 noemt ook onderstaande opdrachten. De uitgewerkte theorie ervan staat niet in deze basismodule; gebruik daarvoor je volgende werkboeken.</p>${data.nextModules.map(m=>`<details><summary>${esc(m.title)}</summary>${list(m.items)}${source(m.page)}</details>`).join('')}</section><section class="card"><h2>Jouw voorbereiding</h2>${list(['Begin met de namen van gereedschappen, auto-onderdelen en de elf lampjes.','Oefen bandencodes, tabelwaarden en de drie hoogteberekeningen.','Beantwoord de open theorievragen in je eigen woorden.','Loop de praktijkopdrachten met de docent na en controleer je handtekeningen.','Herhaal de vragen die je fout had. Een goed quizresultaat bewijst nog niet dat je de praktijk beheerst.'])}</section>`,'examen');document.querySelector('#test').onclick=()=>start(data.topics.flatMap(t=>shuffle(data.questions.filter(q=>q.topic===t.id)).slice(0,5)),'Proeftoets',true);document.querySelector('#open').onclick=openQuestions}
fetch('workbook-data.json',{credentials:'same-origin',redirect:'error'}).then(r=>{if(!r.ok||r.type==='opaqueredirect')throw Error('load');return r.json()}).then(d=>{if(!isValidData(d)||!window.BandenModule)throw Error('invalid-data');const combined={...d,questions:[...d.questions,...window.BandenModule.questions]};if(!isValidData(combined))throw Error('invalid-data');data=combined;home()}).catch(()=>{nav.replaceChildren();app.innerHTML='<section class="card"><h1>Laden is niet gelukt</h1><p>Controleer je verbinding en vernieuw de pagina.</p><button class="btn" id="reload" type="button">Opnieuw proberen</button></section>';document.querySelector('#reload').onclick=()=>location.reload()});
